;; auto-generated by scripts/debug_info_gen_test.py --update
(module

  (func $add_two (param i32 i32) (result i32)

    local.get 0

    local.get 1

    i32.add
;; AARCH64_PASSIVE:         [[@LINE-1]]: 60 02 08 0b  add  w0, w19, w8
;; AARCH64_ACTIVE:          [[@LINE-2]]: 60 02 08 0b  add  w0, w19, w8
;; X86_64_PASSIVE:          [[@LINE-3]]: 8b c5  mov  eax, ebp
;; X86_64_PASSIVE-NEXT:     [[@LINE-4]]: 01 f8  add  eax, edi
;; X86_64_ACTIVE:           [[@LINE-5]]: 8b c5  mov  eax, ebp
;; X86_64_ACTIVE-NEXT:      [[@LINE-6]]: 01 f8  add  eax, edi
;; TRICORE_ACTIVE:          [[@LINE-7]]: 0b 98 00 20  add  d2, d8, d9

    return
;; AARCH64_PASSIVE-NEXT:    [[@LINE-1]]: ff 43 02 91  add  sp, sp, #0x90
;; AARCH64_PASSIVE-NEXT:    [[@LINE-2]]: c0 03 5f d6  ret
;; AARCH64_ACTIVE-NEXT:     [[@LINE-3]]: ff 43 02 91  add  sp, sp, #0x90
;; AARCH64_ACTIVE-NEXT:     [[@LINE-4]]: c0 03 5f d6  ret
;; X86_64_PASSIVE-NEXT:     [[@LINE-5]]: 48 8d a4 24 98 00 00 00  lea  rsp, [rsp + 0x98]
;; X86_64_PASSIVE-NEXT:     [[@LINE-6]]: c3  ret
;; X86_64_ACTIVE-NEXT:      [[@LINE-7]]: 48 8d a4 24 98 00 00 00  lea  rsp, [rsp + 0x98]
;; X86_64_ACTIVE-NEXT:      [[@LINE-8]]: c3  ret
;; TRICORE_ACTIVE-NEXT:     [[@LINE-9]]: d9 aa 14 20  lea  sp, [sp]#0x94
;; TRICORE_ACTIVE-NEXT:     [[@LINE-10]]: 00 70  fret

  )

)

;; DWO_AARCH64_PASSIVE:     -:	file format elf64-littleaarch64
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_abbrev contents:
;; DWO_AARCH64_PASSIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_AARCH64_PASSIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_AARCH64_PASSIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_AARCH64_PASSIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_info contents:
;; DWO_AARCH64_PASSIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_AARCH64_PASSIVE-NEXT:                 DW_AT_low_pc	(0x0000000000000134)
;; DWO_AARCH64_PASSIVE-NEXT:                 DW_AT_high_pc	(0x0000000000000160)
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000001e:   NULL
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_line contents:
;; DWO_AARCH64_PASSIVE-NEXT: debug_line[0x00000000]
;; DWO_AARCH64_PASSIVE-NEXT: Line table prologue:
;; DWO_AARCH64_PASSIVE-NEXT:     total_length: 0x00000051
;; DWO_AARCH64_PASSIVE-NEXT:           format: DWARF32
;; DWO_AARCH64_PASSIVE-NEXT:          version: 5
;; DWO_AARCH64_PASSIVE-NEXT:     address_size: 8
;; DWO_AARCH64_PASSIVE-NEXT:  seg_select_size: 0
;; DWO_AARCH64_PASSIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_AARCH64_PASSIVE-NEXT:  min_inst_length: 1
;; DWO_AARCH64_PASSIVE-NEXT: max_ops_per_inst: 1
;; DWO_AARCH64_PASSIVE-NEXT:  default_is_stmt: 1
;; DWO_AARCH64_PASSIVE-NEXT:        line_base: -3
;; DWO_AARCH64_PASSIVE-NEXT:       line_range: 14
;; DWO_AARCH64_PASSIVE-NEXT:      opcode_base: 5
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_AARCH64_PASSIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_AARCH64_PASSIVE-NEXT: file_names[  0]:
;; DWO_AARCH64_PASSIVE-NEXT:            name: ".wasm"
;; DWO_AARCH64_PASSIVE-NEXT:       dir_index: 0
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_AARCH64_PASSIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000134     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000138     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000013c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000140     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000144     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000148     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000014c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000150     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000154     31      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000158     32      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000015c     32      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000015c     32      0      1   0             0       0  is_stmt end_sequence
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-EMPTY:

;; DWO_AARCH64_ACTIVE:      -:	file format elf64-littleaarch64
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_abbrev contents:
;; DWO_AARCH64_ACTIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_AARCH64_ACTIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_AARCH64_ACTIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_AARCH64_ACTIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_info contents:
;; DWO_AARCH64_ACTIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_AARCH64_ACTIVE-NEXT:                 DW_AT_low_pc	(0x000000000000004c)
;; DWO_AARCH64_ACTIVE-NEXT:                 DW_AT_high_pc	(0x000000000000008c)
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000001e:   NULL
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_line contents:
;; DWO_AARCH64_ACTIVE-NEXT: debug_line[0x00000000]
;; DWO_AARCH64_ACTIVE-NEXT: Line table prologue:
;; DWO_AARCH64_ACTIVE-NEXT:     total_length: 0x0000005f
;; DWO_AARCH64_ACTIVE-NEXT:           format: DWARF32
;; DWO_AARCH64_ACTIVE-NEXT:          version: 5
;; DWO_AARCH64_ACTIVE-NEXT:     address_size: 8
;; DWO_AARCH64_ACTIVE-NEXT:  seg_select_size: 0
;; DWO_AARCH64_ACTIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_AARCH64_ACTIVE-NEXT:  min_inst_length: 1
;; DWO_AARCH64_ACTIVE-NEXT: max_ops_per_inst: 1
;; DWO_AARCH64_ACTIVE-NEXT:  default_is_stmt: 1
;; DWO_AARCH64_ACTIVE-NEXT:        line_base: -3
;; DWO_AARCH64_ACTIVE-NEXT:       line_range: 14
;; DWO_AARCH64_ACTIVE-NEXT:      opcode_base: 5
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_AARCH64_ACTIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_AARCH64_ACTIVE-NEXT: file_names[  0]:
;; DWO_AARCH64_ACTIVE-NEXT:            name: ".wasm"
;; DWO_AARCH64_ACTIVE-NEXT:       dir_index: 0
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_AARCH64_ACTIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000004c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000050     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000054     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000058     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000005c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000060     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000064     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000068     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000006c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000070     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000074     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000078     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000007c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000080     31      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000084     32      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000088     32      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000088     32      0      1   0             0       0  is_stmt end_sequence
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-EMPTY:

;; DWO_X86_64_PASSIVE:      -:	file format elf64-x86-64
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_abbrev contents:
;; DWO_X86_64_PASSIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_X86_64_PASSIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_X86_64_PASSIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_X86_64_PASSIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_info contents:
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_X86_64_PASSIVE-NEXT:                 DW_AT_low_pc	(0x00000000000001ec)
;; DWO_X86_64_PASSIVE-NEXT:                 DW_AT_high_pc	(0x000000000000021f)
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000001e:   NULL
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_line contents:
;; DWO_X86_64_PASSIVE-NEXT: debug_line[0x00000000]
;; DWO_X86_64_PASSIVE-NEXT: Line table prologue:
;; DWO_X86_64_PASSIVE-NEXT:     total_length: 0x00000051
;; DWO_X86_64_PASSIVE-NEXT:           format: DWARF32
;; DWO_X86_64_PASSIVE-NEXT:          version: 5
;; DWO_X86_64_PASSIVE-NEXT:     address_size: 8
;; DWO_X86_64_PASSIVE-NEXT:  seg_select_size: 0
;; DWO_X86_64_PASSIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_X86_64_PASSIVE-NEXT:  min_inst_length: 1
;; DWO_X86_64_PASSIVE-NEXT: max_ops_per_inst: 1
;; DWO_X86_64_PASSIVE-NEXT:  default_is_stmt: 1
;; DWO_X86_64_PASSIVE-NEXT:        line_base: -3
;; DWO_X86_64_PASSIVE-NEXT:       line_range: 14
;; DWO_X86_64_PASSIVE-NEXT:      opcode_base: 5
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_X86_64_PASSIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_X86_64_PASSIVE-NEXT: file_names[  0]:
;; DWO_X86_64_PASSIVE-NEXT:            name: ".wasm"
;; DWO_X86_64_PASSIVE-NEXT:       dir_index: 0
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_X86_64_PASSIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001ec     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001f4     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001fb     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000203     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000207     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000209     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000020d     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000212     31      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000214     31      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000216     32      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000021e     32      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000021e     32      0      1   0             0       0  is_stmt end_sequence
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-EMPTY:

;; DWO_X86_64_ACTIVE:       -:	file format elf64-x86-64
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_abbrev contents:
;; DWO_X86_64_ACTIVE-NEXT:  Abbrev table for offset: 0x00000000
;; DWO_X86_64_ACTIVE-NEXT:  [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_X86_64_ACTIVE-NEXT:  	DW_AT_low_pc	DW_FORM_addr
;; DWO_X86_64_ACTIVE-NEXT:  	DW_AT_high_pc	DW_FORM_addr
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_info contents:
;; DWO_X86_64_ACTIVE-NEXT:  0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000c: DW_TAG_compile_unit
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000d:   DW_TAG_subprogram
;; DWO_X86_64_ACTIVE-NEXT:                  DW_AT_low_pc	(0x0000000000000048)
;; DWO_X86_64_ACTIVE-NEXT:                  DW_AT_high_pc	(0x000000000000008b)
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000001e:   NULL
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_line contents:
;; DWO_X86_64_ACTIVE-NEXT:  debug_line[0x00000000]
;; DWO_X86_64_ACTIVE-NEXT:  Line table prologue:
;; DWO_X86_64_ACTIVE-NEXT:      total_length: 0x0000005c
;; DWO_X86_64_ACTIVE-NEXT:            format: DWARF32
;; DWO_X86_64_ACTIVE-NEXT:           version: 5
;; DWO_X86_64_ACTIVE-NEXT:      address_size: 8
;; DWO_X86_64_ACTIVE-NEXT:   seg_select_size: 0
;; DWO_X86_64_ACTIVE-NEXT:   prologue_length: 0x0000001c
;; DWO_X86_64_ACTIVE-NEXT:   min_inst_length: 1
;; DWO_X86_64_ACTIVE-NEXT:  max_ops_per_inst: 1
;; DWO_X86_64_ACTIVE-NEXT:   default_is_stmt: 1
;; DWO_X86_64_ACTIVE-NEXT:         line_base: -3
;; DWO_X86_64_ACTIVE-NEXT:        line_range: 14
;; DWO_X86_64_ACTIVE-NEXT:       opcode_base: 5
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_X86_64_ACTIVE-NEXT:  include_directories[  0] = "tmp"
;; DWO_X86_64_ACTIVE-NEXT:  file_names[  0]:
;; DWO_X86_64_ACTIVE-NEXT:             name: ".wasm"
;; DWO_X86_64_ACTIVE-NEXT:        dir_index: 0
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_X86_64_ACTIVE-NEXT:  ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000048     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000050     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000054     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000056     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000005b     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000060     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000067     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000006f     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000073     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000075     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000079     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000007e     31      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000080     31      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000082     32      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000008a     32      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000008a     32      0      1   0             0       0  is_stmt end_sequence
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-EMPTY:

;; DWO_TRICORE_ACTIVE:      -:	file format elf64-unknown
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_abbrev contents:
;; DWO_TRICORE_ACTIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_TRICORE_ACTIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_TRICORE_ACTIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_TRICORE_ACTIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_info contents:
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_TRICORE_ACTIVE-NEXT:                 DW_AT_low_pc	(0x0000000000000068)
;; DWO_TRICORE_ACTIVE-NEXT:                 DW_AT_high_pc	(0x00000000000000a0)
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000001e:   NULL
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_line contents:
;; DWO_TRICORE_ACTIVE-NEXT: debug_line[0x00000000]
;; DWO_TRICORE_ACTIVE-NEXT: Line table prologue:
;; DWO_TRICORE_ACTIVE-NEXT:     total_length: 0x0000005f
;; DWO_TRICORE_ACTIVE-NEXT:           format: DWARF32
;; DWO_TRICORE_ACTIVE-NEXT:          version: 5
;; DWO_TRICORE_ACTIVE-NEXT:     address_size: 8
;; DWO_TRICORE_ACTIVE-NEXT:  seg_select_size: 0
;; DWO_TRICORE_ACTIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_TRICORE_ACTIVE-NEXT:  min_inst_length: 1
;; DWO_TRICORE_ACTIVE-NEXT: max_ops_per_inst: 1
;; DWO_TRICORE_ACTIVE-NEXT:  default_is_stmt: 1
;; DWO_TRICORE_ACTIVE-NEXT:        line_base: -3
;; DWO_TRICORE_ACTIVE-NEXT:       line_range: 14
;; DWO_TRICORE_ACTIVE-NEXT:      opcode_base: 5
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_TRICORE_ACTIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_TRICORE_ACTIVE-NEXT: file_names[  0]:
;; DWO_TRICORE_ACTIVE-NEXT:            name: ".wasm"
;; DWO_TRICORE_ACTIVE-NEXT:       dir_index: 0
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_TRICORE_ACTIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000068     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000006a     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000006e     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000072     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000076     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000007a     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000007e     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000082     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000084     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000088     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000008c     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000090     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000092     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000096     31      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000009a     32      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000009e     32      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000009e     32      0      1   0             0       0  is_stmt end_sequence
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-EMPTY:
