;; auto-generated by scripts/debug_info_gen_test.py --update
(module

  (func $if (param i32 i32) (result i32)

    local.get 0

    if (result i32)
;; AARCH64_PASSIVE:         [[@LINE-1]]: 7f 02 00 71  cmp  w19, #0
;; AARCH64_PASSIVE-NEXT:    [[@LINE-2]]: f3 8b 00 b9  str  w19, [sp, #0x88]
;; AARCH64_PASSIVE-NEXT:    [[@LINE-3]]: e8 83 00 b9  str  w8, [sp, #0x80]
;; AARCH64_PASSIVE-NEXT:    [[@LINE-4]]: 60 00 00 54  b.eq  0x16c
;; AARCH64_ACTIVE:          [[@LINE-5]]: 7f 02 00 71  cmp  w19, #0
;; AARCH64_ACTIVE-NEXT:     [[@LINE-6]]: f3 8b 00 b9  str  w19, [sp, #0x88]
;; AARCH64_ACTIVE-NEXT:     [[@LINE-7]]: e8 83 00 b9  str  w8, [sp, #0x80]
;; AARCH64_ACTIVE-NEXT:     [[@LINE-8]]: 60 00 00 54  b.eq  0x98
;; X86_64_PASSIVE:          [[@LINE-9]]: 83 fd 00  cmp  ebp, 0
;; X86_64_PASSIVE-NEXT:     [[@LINE-10]]: 89 ac 24 90 00 00 00  mov  dword ptr [rsp + 0x90], ebp
;; X86_64_PASSIVE-NEXT:     [[@LINE-11]]: 89 bc 24 88 00 00 00  mov  dword ptr [rsp + 0x88], edi
;; X86_64_PASSIVE-NEXT:     [[@LINE-12]]: 0f 84 07 00 00 00  je  0x230
;; X86_64_ACTIVE:           [[@LINE-13]]: 83 fd 00  cmp  ebp, 0
;; X86_64_ACTIVE-NEXT:      [[@LINE-14]]: 89 ac 24 90 00 00 00  mov  dword ptr [rsp + 0x90], ebp
;; X86_64_ACTIVE-NEXT:      [[@LINE-15]]: 89 bc 24 88 00 00 00  mov  dword ptr [rsp + 0x88], edi
;; X86_64_ACTIVE-NEXT:      [[@LINE-16]]: 0f 84 07 00 00 00  je  0x9c
;; TRICORE_ACTIVE:          [[@LINE-17]]: 8b 08 00 62  eq  d6, d8, #0
;; TRICORE_ACTIVE-NEXT:     [[@LINE-18]]: 60 6e  mov.a  a14, d6
;; TRICORE_ACTIVE-NEXT:     [[@LINE-19]]: 59 a8 08 20  st.w  [sp]#0x88, d8
;; TRICORE_ACTIVE-NEXT:     [[@LINE-20]]: 59 a9 00 20  st.w  [sp]#0x80, d9
;; TRICORE_ACTIVE-NEXT:     [[@LINE-21]]: bd 0e 04 00  jz.a  a14, #0xac
;; TRICORE_ACTIVE-NEXT:     [[@LINE-22]]: 1d 00 05 00  j  #0xb2

        local.get 1

    else
;; AARCH64_PASSIVE-NEXT:    [[@LINE-1]]: e0 03 08 2a  mov  w0, w8
;; AARCH64_PASSIVE-NEXT:    [[@LINE-2]]: 02 00 00 14  b  0x170
;; AARCH64_ACTIVE-NEXT:     [[@LINE-3]]: e0 03 08 2a  mov  w0, w8
;; AARCH64_ACTIVE-NEXT:     [[@LINE-4]]: 02 00 00 14  b  0x9c
;; X86_64_PASSIVE-NEXT:     [[@LINE-5]]: 8b c7  mov  eax, edi
;; X86_64_PASSIVE-NEXT:     [[@LINE-6]]: e9 05 00 00 00  jmp  0x235
;; X86_64_ACTIVE-NEXT:      [[@LINE-7]]: 8b c7  mov  eax, edi
;; X86_64_ACTIVE-NEXT:      [[@LINE-8]]: e9 05 00 00 00  jmp  0xa1
;; TRICORE_ACTIVE-NEXT:     [[@LINE-9]]: 02 92  mov  d2, d9
;; TRICORE_ACTIVE-NEXT:     [[@LINE-10]]: 1d 00 03 00  j  #0xb4

        i32.const 0

    end
;; AARCH64_PASSIVE-NEXT:    [[@LINE-1]]: 00 00 80 52  mov  w0, #0
;; AARCH64_PASSIVE-NEXT:    [[@LINE-2]]: ff 43 02 91  add  sp, sp, #0x90
;; AARCH64_PASSIVE-NEXT:    [[@LINE-3]]: c0 03 5f d6  ret
;; AARCH64_ACTIVE-NEXT:     [[@LINE-4]]: 00 00 80 52  mov  w0, #0
;; AARCH64_ACTIVE-NEXT:     [[@LINE-5]]: ff 43 02 91  add  sp, sp, #0x90
;; AARCH64_ACTIVE-NEXT:     [[@LINE-6]]: c0 03 5f d6  ret
;; X86_64_PASSIVE-NEXT:     [[@LINE-7]]: b8 00 00 00 00  mov  eax, 0
;; X86_64_PASSIVE-NEXT:     [[@LINE-8]]: 48 8d a4 24 98 00 00 00  lea  rsp, [rsp + 0x98]
;; X86_64_PASSIVE-NEXT:     [[@LINE-9]]: c3  ret
;; X86_64_ACTIVE-NEXT:      [[@LINE-10]]: b8 00 00 00 00  mov  eax, 0
;; X86_64_ACTIVE-NEXT:      [[@LINE-11]]: 48 8d a4 24 98 00 00 00  lea  rsp, [rsp + 0x98]
;; X86_64_ACTIVE-NEXT:      [[@LINE-12]]: c3  ret
;; TRICORE_ACTIVE-NEXT:     [[@LINE-13]]: 82 02  mov  d2, #0
;; TRICORE_ACTIVE-NEXT:     [[@LINE-14]]: d9 aa 14 20  lea  sp, [sp]#0x94
;; TRICORE_ACTIVE-NEXT:     [[@LINE-15]]: 00 70  fret

  )

)

;; DWO_AARCH64_PASSIVE:     -:	file format elf64-littleaarch64
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_abbrev contents:
;; DWO_AARCH64_PASSIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_AARCH64_PASSIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_AARCH64_PASSIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_AARCH64_PASSIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_info contents:
;; DWO_AARCH64_PASSIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_AARCH64_PASSIVE-NEXT:                 DW_AT_low_pc	(0x0000000000000134)
;; DWO_AARCH64_PASSIVE-NEXT:                 DW_AT_high_pc	(0x0000000000000178)
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000001e:   NULL
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: .debug_line contents:
;; DWO_AARCH64_PASSIVE-NEXT: debug_line[0x00000000]
;; DWO_AARCH64_PASSIVE-NEXT: Line table prologue:
;; DWO_AARCH64_PASSIVE-NEXT:     total_length: 0x00000067
;; DWO_AARCH64_PASSIVE-NEXT:           format: DWARF32
;; DWO_AARCH64_PASSIVE-NEXT:          version: 5
;; DWO_AARCH64_PASSIVE-NEXT:     address_size: 8
;; DWO_AARCH64_PASSIVE-NEXT:  seg_select_size: 0
;; DWO_AARCH64_PASSIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_AARCH64_PASSIVE-NEXT:  min_inst_length: 1
;; DWO_AARCH64_PASSIVE-NEXT: max_ops_per_inst: 1
;; DWO_AARCH64_PASSIVE-NEXT:  default_is_stmt: 1
;; DWO_AARCH64_PASSIVE-NEXT:        line_base: -3
;; DWO_AARCH64_PASSIVE-NEXT:       line_range: 14
;; DWO_AARCH64_PASSIVE-NEXT:      opcode_base: 5
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_AARCH64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_AARCH64_PASSIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_AARCH64_PASSIVE-NEXT: file_names[  0]:
;; DWO_AARCH64_PASSIVE-NEXT:            name: ".wasm"
;; DWO_AARCH64_PASSIVE-NEXT:       dir_index: 0
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_AARCH64_PASSIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000134     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000138     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000013c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000140     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000144     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000148     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000014c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000150     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000154     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000158     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000015c     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000160     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000164     33      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000168     33      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x000000000000016c     36      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000170     37      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000174     37      0      1   0             0       0  is_stmt
;; DWO_AARCH64_PASSIVE-NEXT: 0x0000000000000174     37      0      1   0             0       0  is_stmt end_sequence
;; DWO_AARCH64_PASSIVE-EMPTY:
;; DWO_AARCH64_PASSIVE-EMPTY:

;; DWO_AARCH64_ACTIVE:      -:	file format elf64-littleaarch64
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_abbrev contents:
;; DWO_AARCH64_ACTIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_AARCH64_ACTIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_AARCH64_ACTIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_AARCH64_ACTIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_info contents:
;; DWO_AARCH64_ACTIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_AARCH64_ACTIVE-NEXT:                 DW_AT_low_pc	(0x000000000000004c)
;; DWO_AARCH64_ACTIVE-NEXT:                 DW_AT_high_pc	(0x00000000000000a4)
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000001e:   NULL
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: .debug_line contents:
;; DWO_AARCH64_ACTIVE-NEXT: debug_line[0x00000000]
;; DWO_AARCH64_ACTIVE-NEXT: Line table prologue:
;; DWO_AARCH64_ACTIVE-NEXT:     total_length: 0x00000075
;; DWO_AARCH64_ACTIVE-NEXT:           format: DWARF32
;; DWO_AARCH64_ACTIVE-NEXT:          version: 5
;; DWO_AARCH64_ACTIVE-NEXT:     address_size: 8
;; DWO_AARCH64_ACTIVE-NEXT:  seg_select_size: 0
;; DWO_AARCH64_ACTIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_AARCH64_ACTIVE-NEXT:  min_inst_length: 1
;; DWO_AARCH64_ACTIVE-NEXT: max_ops_per_inst: 1
;; DWO_AARCH64_ACTIVE-NEXT:  default_is_stmt: 1
;; DWO_AARCH64_ACTIVE-NEXT:        line_base: -3
;; DWO_AARCH64_ACTIVE-NEXT:       line_range: 14
;; DWO_AARCH64_ACTIVE-NEXT:      opcode_base: 5
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_AARCH64_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_AARCH64_ACTIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_AARCH64_ACTIVE-NEXT: file_names[  0]:
;; DWO_AARCH64_ACTIVE-NEXT:            name: ".wasm"
;; DWO_AARCH64_ACTIVE-NEXT:       dir_index: 0
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_AARCH64_ACTIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000004c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000050     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000054     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000058     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000005c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000060     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000064     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000068     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000006c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000070     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000074     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000078     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000007c     26      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000080     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000084     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000088     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000008c     29      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000090     33      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000094     33      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x0000000000000098     36      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x000000000000009c     37      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x00000000000000a0     37      0      1   0             0       0  is_stmt
;; DWO_AARCH64_ACTIVE-NEXT: 0x00000000000000a0     37      0      1   0             0       0  is_stmt end_sequence
;; DWO_AARCH64_ACTIVE-EMPTY:
;; DWO_AARCH64_ACTIVE-EMPTY:

;; DWO_X86_64_PASSIVE:      -:	file format elf64-x86-64
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_abbrev contents:
;; DWO_X86_64_PASSIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_X86_64_PASSIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_X86_64_PASSIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_X86_64_PASSIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_info contents:
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_X86_64_PASSIVE-NEXT:                 DW_AT_low_pc	(0x00000000000001ec)
;; DWO_X86_64_PASSIVE-NEXT:                 DW_AT_high_pc	(0x000000000000023e)
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: 0x0000001e:   NULL
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: .debug_line contents:
;; DWO_X86_64_PASSIVE-NEXT: debug_line[0x00000000]
;; DWO_X86_64_PASSIVE-NEXT: Line table prologue:
;; DWO_X86_64_PASSIVE-NEXT:     total_length: 0x00000064
;; DWO_X86_64_PASSIVE-NEXT:           format: DWARF32
;; DWO_X86_64_PASSIVE-NEXT:          version: 5
;; DWO_X86_64_PASSIVE-NEXT:     address_size: 8
;; DWO_X86_64_PASSIVE-NEXT:  seg_select_size: 0
;; DWO_X86_64_PASSIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_X86_64_PASSIVE-NEXT:  min_inst_length: 1
;; DWO_X86_64_PASSIVE-NEXT: max_ops_per_inst: 1
;; DWO_X86_64_PASSIVE-NEXT:  default_is_stmt: 1
;; DWO_X86_64_PASSIVE-NEXT:        line_base: -3
;; DWO_X86_64_PASSIVE-NEXT:       line_range: 14
;; DWO_X86_64_PASSIVE-NEXT:      opcode_base: 5
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_X86_64_PASSIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_X86_64_PASSIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_X86_64_PASSIVE-NEXT: file_names[  0]:
;; DWO_X86_64_PASSIVE-NEXT:            name: ".wasm"
;; DWO_X86_64_PASSIVE-NEXT:       dir_index: 0
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_X86_64_PASSIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001ec     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001f4     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x00000000000001fb     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000203     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000207     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000209     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000020d     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000212     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000215     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000021c     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000223     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000229     33      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000022b     33      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000230     36      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x0000000000000235     37      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000023d     37      0      1   0             0       0  is_stmt
;; DWO_X86_64_PASSIVE-NEXT: 0x000000000000023d     37      0      1   0             0       0  is_stmt end_sequence
;; DWO_X86_64_PASSIVE-EMPTY:
;; DWO_X86_64_PASSIVE-EMPTY:

;; DWO_X86_64_ACTIVE:       -:	file format elf64-x86-64
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_abbrev contents:
;; DWO_X86_64_ACTIVE-NEXT:  Abbrev table for offset: 0x00000000
;; DWO_X86_64_ACTIVE-NEXT:  [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_X86_64_ACTIVE-NEXT:  	DW_AT_low_pc	DW_FORM_addr
;; DWO_X86_64_ACTIVE-NEXT:  	DW_AT_high_pc	DW_FORM_addr
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_info contents:
;; DWO_X86_64_ACTIVE-NEXT:  0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000c: DW_TAG_compile_unit
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000d:   DW_TAG_subprogram
;; DWO_X86_64_ACTIVE-NEXT:                  DW_AT_low_pc	(0x0000000000000048)
;; DWO_X86_64_ACTIVE-NEXT:                  DW_AT_high_pc	(0x00000000000000aa)
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  0x0000001e:   NULL
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  .debug_line contents:
;; DWO_X86_64_ACTIVE-NEXT:  debug_line[0x00000000]
;; DWO_X86_64_ACTIVE-NEXT:  Line table prologue:
;; DWO_X86_64_ACTIVE-NEXT:      total_length: 0x0000006f
;; DWO_X86_64_ACTIVE-NEXT:            format: DWARF32
;; DWO_X86_64_ACTIVE-NEXT:           version: 5
;; DWO_X86_64_ACTIVE-NEXT:      address_size: 8
;; DWO_X86_64_ACTIVE-NEXT:   seg_select_size: 0
;; DWO_X86_64_ACTIVE-NEXT:   prologue_length: 0x0000001c
;; DWO_X86_64_ACTIVE-NEXT:   min_inst_length: 1
;; DWO_X86_64_ACTIVE-NEXT:  max_ops_per_inst: 1
;; DWO_X86_64_ACTIVE-NEXT:   default_is_stmt: 1
;; DWO_X86_64_ACTIVE-NEXT:         line_base: -3
;; DWO_X86_64_ACTIVE-NEXT:        line_range: 14
;; DWO_X86_64_ACTIVE-NEXT:       opcode_base: 5
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_X86_64_ACTIVE-NEXT:  standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_X86_64_ACTIVE-NEXT:  include_directories[  0] = "tmp"
;; DWO_X86_64_ACTIVE-NEXT:  file_names[  0]:
;; DWO_X86_64_ACTIVE-NEXT:             name: ".wasm"
;; DWO_X86_64_ACTIVE-NEXT:        dir_index: 0
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-NEXT:  Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_X86_64_ACTIVE-NEXT:  ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000048     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000050     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000054     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000056     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000005b     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000060     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000067     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000006f     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000073     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000075     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000079     26      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000007e     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000081     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000088     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000008f     29      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000095     33      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x0000000000000097     33      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x000000000000009c     36      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x00000000000000a1     37      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x00000000000000a9     37      0      1   0             0       0  is_stmt
;; DWO_X86_64_ACTIVE-NEXT:  0x00000000000000a9     37      0      1   0             0       0  is_stmt end_sequence
;; DWO_X86_64_ACTIVE-EMPTY:
;; DWO_X86_64_ACTIVE-EMPTY:

;; DWO_TRICORE_ACTIVE:      -:	file format elf64-unknown
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_abbrev contents:
;; DWO_TRICORE_ACTIVE-NEXT: Abbrev table for offset: 0x00000000
;; DWO_TRICORE_ACTIVE-NEXT: [1] DW_TAG_compile_unit	DW_CHILDREN_yes
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: [2] DW_TAG_subprogram	DW_CHILDREN_no
;; DWO_TRICORE_ACTIVE-NEXT: 	DW_AT_low_pc	DW_FORM_addr
;; DWO_TRICORE_ACTIVE-NEXT: 	DW_AT_high_pc	DW_FORM_addr
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_info contents:
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000: Compile Unit: length = 0x0000001b, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000001f)
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000c: DW_TAG_compile_unit
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000d:   DW_TAG_subprogram
;; DWO_TRICORE_ACTIVE-NEXT:                 DW_AT_low_pc	(0x0000000000000068)
;; DWO_TRICORE_ACTIVE-NEXT:                 DW_AT_high_pc	(0x00000000000000ba)
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000001e:   NULL
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: .debug_line contents:
;; DWO_TRICORE_ACTIVE-NEXT: debug_line[0x00000000]
;; DWO_TRICORE_ACTIVE-NEXT: Line table prologue:
;; DWO_TRICORE_ACTIVE-NEXT:     total_length: 0x0000007b
;; DWO_TRICORE_ACTIVE-NEXT:           format: DWARF32
;; DWO_TRICORE_ACTIVE-NEXT:          version: 5
;; DWO_TRICORE_ACTIVE-NEXT:     address_size: 8
;; DWO_TRICORE_ACTIVE-NEXT:  seg_select_size: 0
;; DWO_TRICORE_ACTIVE-NEXT:  prologue_length: 0x0000001c
;; DWO_TRICORE_ACTIVE-NEXT:  min_inst_length: 1
;; DWO_TRICORE_ACTIVE-NEXT: max_ops_per_inst: 1
;; DWO_TRICORE_ACTIVE-NEXT:  default_is_stmt: 1
;; DWO_TRICORE_ACTIVE-NEXT:        line_base: -3
;; DWO_TRICORE_ACTIVE-NEXT:       line_range: 14
;; DWO_TRICORE_ACTIVE-NEXT:      opcode_base: 5
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_copy] = 0
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_pc] = 1
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_advance_line] = 1
;; DWO_TRICORE_ACTIVE-NEXT: standard_opcode_lengths[DW_LNS_set_file] = 1
;; DWO_TRICORE_ACTIVE-NEXT: include_directories[  0] = "tmp"
;; DWO_TRICORE_ACTIVE-NEXT: file_names[  0]:
;; DWO_TRICORE_ACTIVE-NEXT:            name: ".wasm"
;; DWO_TRICORE_ACTIVE-NEXT:       dir_index: 0
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-NEXT: Address            Line   Column File   ISA Discriminator OpIndex Flags
;; DWO_TRICORE_ACTIVE-NEXT: ------------------ ------ ------ ------ --- ------------- ------- -------------
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000068     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000006a     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000006e     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000072     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000076     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000007a     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000007e     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000082     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000084     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000088     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000008c     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000090     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000092     26      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x0000000000000096     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000009a     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x000000000000009c     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000a0     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000a4     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000a8     29      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000ac     33      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000ae     33      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000b2     36      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000b4     37      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000b8     37      0      1   0             0       0  is_stmt
;; DWO_TRICORE_ACTIVE-NEXT: 0x00000000000000b8     37      0      1   0             0       0  is_stmt end_sequence
;; DWO_TRICORE_ACTIVE-EMPTY:
;; DWO_TRICORE_ACTIVE-EMPTY:
