set(_IMPORT_PREFIX ${CMAKE_CURRENT_LIST_DIR})

set(VB_WASM_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}" "${CMAKE_CURRENT_LIST_DIR}/wasm-compiler")


add_library(@PROJECT_NAME@ STATIC IMPORTED)
      

set(VB_WASM_LIBRARIES @installTargets@)

link_directories(${CMAKE_CURRENT_LIST_DIR}/lib)

set_target_properties(@PROJECT_NAME@ PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${VB_WASM_INCLUDE_DIRS}"
    IMPORTED_IMPLIB "${VB_WASM_LIBRARIES}"
)

set(_IMPORT_PREFIX)