name: execute

on:
  workflow_call:
    inputs:
      arch:
        description: CPU arch to run the workflow on (x86_64, aarch64, tricore).
        type: string
        required: true
      os:
        description: OS to run the workflow on (linux only).
        type: string
        required: true
      run:
        description: Run commands in native environment.
        required: true
        type: string

jobs:
  check_os:
    runs-on: ubuntu-latest
    steps:
      - name: Check OS input
        run: |
          if [ "${{ inputs.os }}" != "linux" ]; then
            echo "Error: Only linux is supported for this workflow."
            exit 1
          fi
  qemu-tricore:
    if: ${{ inputs.arch == 'tricore' }}
    runs-on: ${{ github.repository_owner == 'wasm-ecosystem' && 'ubuntu-latest' || 'cawe-linux-x64-compute-large' }}
    container:
      image: ubuntu:24.04
      options: --user root
    steps:
      - name: Install dependencies
        run: |
          apt-get update -y -qq
          apt-get install -y --no-install-recommends \
          build-essential ca-certificates cmake git jq clang llvm llvm-18-tools libclang-rt-18-dev clang-tidy \
          texinfo bison flex libdebuginfod-dev python-is-python3 gcovr \
          p7zip-full libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build wget \
          python3-dev python3-venv python3 python3-pip binaryen
      - name: Install wabt
        run: |
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.36/wabt-1.0.36-ubuntu-20.04.tar.gz
          tar -xzf wabt-1.0.36-ubuntu-20.04.tar.gz
          echo "$PWD/wabt-1.0.36/bin" >> $GITHUB_PATH
      - name: Install tricore gcc
        run: |
          git clone --depth=1 https://github.com/volumit/tricore_gcc940_linux_bins.git
          cd tricore_gcc940_linux_bins
          7z x tricore_940_linux.zip.001
          chmod -R 777 tricore_940_linux
          ln -s $(pwd)/tricore_940_linux/bin/tricore-elf-gcc /usr/bin/tricore-elf-gcc
          ln -s $(pwd)/tricore_940_linux/bin/tricore-elf-g++ /usr/bin/tricore-elf-g++
      - name: Install tricore qemu
        run: |
          wget https://github.com/Schleifner/qemu/releases/download/release-tc18-2/qemu-system-tricore
          chmod +x qemu-system-tricore
          mv qemu-system-tricore /usr/local/bin/qemu-system-tricore
      - name: Install Googletest
        run: |
          git clone --depth 1 --branch release-1.11.0 https://github.com/google/googletest.git \
          && cd googletest && mkdir build && cd build && cmake .. && make -j $(nproc) && make install
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          path: source-repo
          submodules: true
      - name: run native commands
        working-directory: source-repo
        shell: bash
        run: |
          ${{ inputs.run }}

  linux_native:
    if: ${{ inputs.arch != 'tricore' }}
    runs-on: ${{ github.repository_owner == 'wasm-ecosystem' && (inputs.arch == 'x86_64' && 'ubuntu-latest' || inputs.arch == 'aarch64' && 'ubuntu-24.04-arm') || inputs.arch == 'x86_64' && 'cawe-linux-x64-compute-large' || inputs.arch == 'aarch64' && 'cawe-linux-arm64-compute-large' }}
    container:
      image: ubuntu:24.04
      options: --user root
    steps:
      - name: setup ubuntu
        run: sysctl vm.mmap_rnd_bits=28
      - name: Install dependencies
        run: |
          apt-get update -y -qq
          apt-get install -y --no-install-recommends \
          build-essential ca-certificates cmake git jq clang llvm llvm-18-tools libclang-rt-18-dev clang-tidy \
          texinfo bison flex libdebuginfod-dev python-is-python3 gcovr \
          p7zip-full libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build wget \
          python3-dev python3-venv python3 python3-pip binaryen

          if [ "${{ inputs.arch }}" = "x86_64" ]; then
            apt-get install -y --no-install-recommends \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-11-aarch64-linux-gnu g++-11-aarch64-linux-gnu
          fi
      - name: Install Googletest
        run: |
          git clone --depth 1 --branch release-1.11.0 https://github.com/google/googletest.git \
          && cd googletest && mkdir build && cd build && cmake .. && make -j $(nproc) && make install
      - name: Install wabt
        run: |
          if [ "${{ inputs.arch }}" = "aarch64" ]; then
            wget https://github.com/Schleifner/wabt/releases/download/release-1.0.36/wabt-85283774695bde90033d33e98a810f8448d53964-ubuntu-24.04-arm.tar.gz
            tar -xzf wabt-85283774695bde90033d33e98a810f8448d53964-ubuntu-24.04-arm.tar.gz
            echo "$PWD/wabt-85283774695bde90033d33e98a810f8448d53964/bin" >> $GITHUB_PATH
          else
            wget https://github.com/WebAssembly/wabt/releases/download/1.0.36/wabt-1.0.36-ubuntu-20.04.tar.gz
            tar -xzf wabt-1.0.36-ubuntu-20.04.tar.gz
            echo "$PWD/wabt-1.0.36/bin" >> $GITHUB_PATH
          fi
      - name: Install bazel
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/7.0.0/bazel-7.0.0-linux-x86_64
          mv bazel-7.0.0-linux-x86_64 /usr/local/bin/bazel
          chmod 777 /usr/local/bin/bazel
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          path: source-repo
          submodules: true
      - name: run native commands
        working-directory: source-repo
        shell: bash
        run: |
          ${{ inputs.run }}