name: Public GitHub

on:
  push:
    branches:
      - master
      - develop
      - 'release/*'
  pull_request:
    branches:
      - master
      - develop
      - 'release/*'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  aarch64_windows_cmake_build_test:
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - Compiler_type: aarch64_debug_msvc
            cmake_arguments: -DVB_ENABLE_DEV_FEATURE=OFF -DENABLE_MSVC_PARALLEL=0 -DENABLE_WERROR=1 -A ARM64 -DENABLE_SPECTEST=1 -DENABLE_DEMO=1
            Build_type: Debug
          - Compiler_type: aarch64_relwithdebinfo_msvc
            cmake_arguments: -DVB_ENABLE_DEV_FEATURE=OFF -DENABLE_MSVC_PARALLEL=0 -DENABLE_WERROR=1 -A ARM64 -DENABLE_SPECTEST=1 -DENABLE_DEMO=1
            Build_type: RelWithDebInfo
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # Here x86_64 executable file can be used because windows has instruction emulator.
      - name: Install wabt
        run: |
          aria2c https://github.com/WebAssembly/wabt/releases/download/1.0.36/wabt-1.0.36-windows.tar.gz
          tar -xzf wabt-1.0.36-windows.tar.gz
          mv wabt-1.0.36 C:\wabt-1.0.36
          echo "C:\wabt-1.0.36\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: gen testcase
        run: python tests/spectest.py
      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.cmake_arguments }}
          cmake --build . --config ${{ matrix.Build_type }}
          ctest --verbose -C ${{ matrix.Build_type }}

  aarch64_android_cmake_build_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install cmake wabt

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        run: |
          set -ex
          brew install --cask android-commandlinetools
          echo "ANDROID_SDK_ROOT=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV
          echo "ANDROID_HOME=$(brew --prefix)/share/android-commandlinetools" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android NDK and emulator
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.2.12479018" "emulator" "platform-tools" "system-images;android-35;google_apis;arm64-v8a"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV

      - name: Create Android virtual device
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n arm64_emulator -k "system-images;android-35;google_apis;arm64-v8a" -d "pixel_6"

      - name: gen testcase
        run: python3 tests/spectest.py

      - name: Build for Android
        run: |
          cmake -DVB_ENABLE_DEV_FEATURE=OFF -DENABLE_SPECTEST=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-35 -B build_android
          cmake --build build_android --parallel

      - name: Run Android tests
        run: |
          python3 ./scripts/android/android_test.py --avd arm64_emulator
