name: Release

on:
  push:
    tags:
      - "*"

env:
  package_name: wasm-compiler-${{ github.ref_name }}.tar.gz
jobs:
  release:
    runs-on: [atc-ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: get release body
        id: releaseBodyStep
        run: |
          release_body=$(sed -n '/^## /{ :a; n; /^## /q; p; ba; }' RELEASENOTES.md)
          echo -e "Release_body<<EOF\n$release_body\nEOF" >> $GITHUB_OUTPUT

      - name: compress
        run: scripts/archive.sh
        env:
          package_name: ${{ env.package_name }}

      - name: upload to ddad artifactory
        run: |
          curl -u ${{ secrets.TECH_USER_CODECRAFT_ACCOUNT }}:${{ secrets.TECH_USER_DDAD_ARTIFACTORY_TOKEN }} --upload-file "./${{ env.package_name }}" "https://${{ vars.INTERNAL_ARTIFACTORY_WARP_PATH }}/${{ env.package_name }}"

      - name: create release
        id: createRelease
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.releaseBodyStep.outputs.Release_body }}

      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./${{ env.package_name }}"]'
